const n5Grammar = [
  { japanese: { main: ['ああ'], other: [], kanji: [] }, english: { main: ['Ah!'], other: [] } },
  { japanese: { main: ['あう'], other: [], kanji: ['会う'] }, english: { main: ['to meet'], other: [] } },
  { japanese: { main: ['あおい'], other: [], kanji: ['青い'] }, english: { main: ['blue'], other: [] } },
  { japanese: { main: ['あかい'], other: [], kanji: ['赤い'] }, english: { main: ['red'], other: [] } },
  { japanese: { main: ['あかるい'], other: [], kanji: ['明るい'] }, english: { main: ['light'], other: ['bright'] } },
  { japanese: { main: ['あき'], other: [], kanji: ['秋'] }, english: { main: ['autumn'], other: ['fall'] } },
  { japanese: { main: ['あく'], other: [], kanji: ['開く'] }, english: { main: ['open'], other: [] } },
  { japanese: { main: ['あける'], other: [], kanji: ['開ける'] }, english: { main: ['to open'], other: [] } },
  { japanese: { main: ['あげる'], other: [], kanji: [] }, english: { main: ['to give'], other: [] } },
  { japanese: { main: ['あさ'], other: [], kanji: ['朝'] }, english: { main: ['morning'], other: [] } },
  { japanese: { main: ['あさごはん'], other: [], kanji: ['朝ご飯'] }, english: { main: ['breakfast'], other: [] } },
  { japanese: { main: ['あさって'], other: [], kanji: [] }, english: { main: ['the day after tomorrow'], other: [] } },
  { japanese: { main: ['あし'], other: [], kanji: ['足'] }, english: { main: ['leg'], other: ['foot'] } },
  { japanese: { main: ['あした'], other: [], kanji: ['明日'] }, english: { main: ['tomorrow'], other: [] } },
  { japanese: { main: ['あそこ'], other: [], kanji: [] }, english: { main: ['over there'], other: [] } },
  { japanese: { main: ['あそぶ'], other: [], kanji: ['遊ぶ'] }, english: { main: ['to play'], other: [] } },
  { japanese: { main: ['あたたかい'], other: [], kanji: ['温かい'] }, english: { main: ['warm'], other: [] } },
  { japanese: { main: ['あたま'], other: [], kanji: ['頭'] }, english: { main: ['head'], other: [] } },
  { japanese: { main: ['あたらしい'], other: [], kanji: ['新しい'] }, english: { main: ['new'], other: [] } },
  { japanese: { main: ['あちら'], other: [], kanji: [] }, english: { main: ['over there (polite)'], other: [] } },
  { japanese: { main: ['あつい'], other: [], kanji: ['暑い'] }, english: { main: ['hot (air)'], other: [] } },
  { japanese: { main: ['あつい'], other: [], kanji: ['厚い'] }, english: { main: ['thick'], other: [] } },
  { japanese: { main: ['あと'], other: [], kanji: ['後'] }, english: { main: ['later'], other: ['after'] } },
  { japanese: { main: ['あなた'], other: [], kanji: ['貴方'] }, english: { main: ['you'], other: [] } },
  { japanese: { main: ['あに'], other: [], kanji: ['兄'] }, english: { main: ['older brother'], other: [] } },
  { japanese: { main: ['あね'], other: [], kanji: ['姉'] }, english: { main: ['older sister'], other: [] } },
  { japanese: { main: ['あの'], other: [], kanji: [] }, english: { main: ['that (over there)'], other: [] } },
  { japanese: { main: ['あの'], other: [], kanji: [] }, english: { main: ['well'], other: ['then'] } },
  { japanese: { main: ['アパート'], other: [], kanji: [] }, english: { main: ['apartment'], other: [] } },
  { japanese: { main: ['あびる'], other: [], kanji: ['浴びる'] }, english: { main: ['to take a shower'], other: [] } },
  { japanese: { main: ['あぶない'], other: [], kanji: ['危ない'] }, english: { main: ['dangerous'], other: [] } },
  { japanese: { main: ['あまい'], other: [], kanji: ['甘い'] }, english: { main: ['sweet'], other: [] } },
  { japanese: { main: ['あまり'], other: [], kanji: [] }, english: { main: ['not so'], other: [] } },
  { japanese: { main: ['あめ'], other: [], kanji: ['雨'] }, english: { main: ['rain'], other: [] } },
  { japanese: { main: ['あらう'], other: [], kanji: ['洗う'] }, english: { main: ['to wash'], other: [] } },
  { japanese: { main: ['ある'], other: [], kanji: ['有る'] }, english: { main: ['to be'], other: ['to exist'] } },
  { japanese: { main: ['ある'], other: [], kanji: [] }, english: { main: ['to possess'], other: [] } },
  { japanese: { main: ['あるく'], other: [], kanji: ['歩く'] }, english: { main: ['to walk'], other: [] } },
  { japanese: { main: ['あれ'], other: [], kanji: [] }, english: { main: ['that one'], other: [] } },
  { japanese: { main: ['いい / よい'], other: [], kanji: ['良い'] }, english: { main: ['good'], other: [] } },
  { japanese: { main: ['いいえ'], other: [], kanji: [] }, english: { main: ['no'], other: [] } },
  { japanese: { main: ['いう'], other: [], kanji: ['言う'] }, english: { main: ['to say'], other: ['to tell'] } },
  { japanese: { main: ['いえ'], other: [], kanji: ['家'] }, english: { main: ['house'], other: ['home'] } },
  { japanese: { main: ['いく'], other: [], kanji: ['行く'] }, english: { main: ['to go'], other: [] } },
  { japanese: { main: ['いくつ'], other: [], kanji: [] }, english: { main: ['how many'], other: ['how old'] } },
  { japanese: { main: ['いくら'], other: [], kanji: [] }, english: { main: ['how much'], other: [] } },
  { japanese: { main: ['いけ'], other: [], kanji: ['池'] }, english: { main: ['pond'], other: [] } },
  { japanese: { main: ['いしゃ'], other: [], kanji: ['医者'] }, english: { main: ['doctor'], other: [] } },
  { japanese: { main: ['いす'], other: [], kanji: ['椅子'] }, english: { main: ['chair'], other: [] } },
  { japanese: { main: ['いそがしい'], other: [], kanji: ['忙しい'] }, english: { main: ['to be busy'], other: [] } },
  { japanese: { main: ['いたい'], other: [], kanji: ['痛い'] }, english: { main: ['to be painful'], other: [] } },
  { japanese: { main: ['いち'], other: [], kanji: ['一'] }, english: { main: ['one'], other: [] } },
  { japanese: { main: ['いちにち'], other: [], kanji: ['一日'] }, english: { main: ['one day'], other: [] } },
  {
    japanese: { main: ['いちばん'], other: [], kanji: ['一番'] },
    english: { main: ['No. 1'], other: ['the best', ' the first'] },
  },
  { japanese: { main: ['いつ'], other: [], kanji: [] }, english: { main: ['when'], other: [] } },
  {
    japanese: { main: ['いつか'], other: [], kanji: ['五日'] },
    english: { main: ['the 5th day of the month'], other: ['5 days'] },
  },
  { japanese: { main: ['いっしょ'], other: [], kanji: ['一緒'] }, english: { main: ['together'], other: [] } },
  { japanese: { main: ['いつつ'], other: [], kanji: ['五つ'] }, english: { main: ['five'], other: [] } },
  { japanese: { main: ['いつも'], other: [], kanji: [] }, english: { main: ['always'], other: [] } },
  { japanese: { main: ['いま'], other: [], kanji: ['今'] }, english: { main: ['now'], other: [] } },
  { japanese: { main: ['いみ'], other: [], kanji: ['意味'] }, english: { main: ['meaning'], other: [] } },
  {
    japanese: { main: ['いもうと'], other: [], kanji: ['妹'] },
    english: { main: ['someone’s younger sister'], other: [] },
  },
  { japanese: { main: ['いや'], other: [], kanji: [] }, english: { main: ['not likable'], other: ['unpleasant'] } },
  { japanese: { main: ['いりぐち'], other: [], kanji: ['入口'] }, english: { main: ['entrance'], other: [] } },
  {
    japanese: { main: ['いる'], other: [], kanji: [] },
    english: { main: ['need'], other: ['must have', ' be required'] },
  },
  { japanese: { main: ['いる'], other: [], kanji: [] }, english: { main: ['to exist'], other: [] } },
  {
    japanese: { main: ['いれる'], other: [], kanji: ['入れる'] },
    english: { main: ['to insert'], other: ['to put in'] },
  },
  { japanese: { main: ['いろ'], other: [], kanji: ['色'] }, english: { main: ['color'], other: [] } },
  { japanese: { main: ['いろいろ'], other: [], kanji: ['色々'] }, english: { main: ['various'], other: [] } },
  { japanese: { main: ['うえ'], other: [], kanji: ['上'] }, english: { main: ['top'], other: ['on', ' above'] } },
  {
    japanese: { main: ['うしろ'], other: [], kanji: ['後ろ'] },
    english: { main: ['back'], other: ['rear', ' behind'] },
  },
  { japanese: { main: ['うすい'], other: [], kanji: ['薄い'] }, english: { main: ['thin'], other: [] } },
  { japanese: { main: ['うた'], other: [], kanji: ['歌'] }, english: { main: ['song'], other: [] } },
  { japanese: { main: ['うたう'], other: [], kanji: ['歌う'] }, english: { main: ['to sing'], other: [] } },
  { japanese: { main: ['うち'], other: [], kanji: ['内'] }, english: { main: ['home'], other: [] } },
  { japanese: { main: ['うまれる'], other: [], kanji: ['生まれる'] }, english: { main: ['to be born'], other: [] } },
  { japanese: { main: ['うみ'], other: [], kanji: ['海'] }, english: { main: ['sea'], other: [] } },
  { japanese: { main: ['うる'], other: [], kanji: ['売る'] }, english: { main: ['to sell'], other: [] } },
  { japanese: { main: ['うわぎ'], other: [], kanji: ['上着'] }, english: { main: ['coat'], other: ['jacket'] } },
  { japanese: { main: ['え'], other: [], kanji: ['絵'] }, english: { main: ['picture'], other: [] } },
  { japanese: { main: ['えいが'], other: [], kanji: ['映画'] }, english: { main: ['movie'], other: [] } },
  { japanese: { main: ['えいがかん'], other: [], kanji: ['映画館'] }, english: { main: ['cinema'], other: [] } },
  { japanese: { main: ['えいご'], other: [], kanji: ['英語'] }, english: { main: ['English language'], other: [] } },
  { japanese: { main: ['ええ'], other: [], kanji: [] }, english: { main: ['Yes'], other: ['I see'] } },
  { japanese: { main: ['えき'], other: [], kanji: ['駅'] }, english: { main: ['station'], other: [] } },
  { japanese: { main: ['エレベータ'], other: [], kanji: [] }, english: { main: ['elevator'], other: [] } },
  { japanese: { main: ['えん'], other: [], kanji: ['円'] }, english: { main: ['Yen'], other: [] } },
  { japanese: { main: ['えんぴつ'], other: [], kanji: ['鉛筆'] }, english: { main: ['pencil'], other: [] } },
  { japanese: { main: ['お'], other: [], kanji: ['御'] }, english: { main: ['honorific prefix'], other: [] } },
  {
    japanese: { main: ['おいしい'], other: [], kanji: ['美味しい'] },
    english: { main: ['tasty'], other: ['delicious'] },
  },
  { japanese: { main: ['おおきい'], other: [], kanji: ['大きい'] }, english: { main: ['big'], other: [] } },
  { japanese: { main: ['おおぜい'], other: [], kanji: [] }, english: { main: ['many people'], other: [] } },
  {
    japanese: { main: ['おかあさん'], other: [], kanji: ['お母さん'] },
    english: { main: ['my own mother'], other: [] },
  },
  {
    japanese: { main: ['おかし'], other: [], kanji: ['お菓子'] },
    english: { main: ['confectionary'], other: ['cake'] },
  },
  { japanese: { main: ['おかね'], other: [], kanji: ['お金'] }, english: { main: ['money'], other: [] } },
  {
    japanese: { main: ['おきる'], other: [], kanji: ['起きる'] },
    english: { main: ['to get up'], other: ['to stand up'] },
  },
  { japanese: { main: ['おく'], other: [], kanji: ['置く'] }, english: { main: ['to put'], other: ['to place'] } },
  { japanese: { main: ['おくさん'], other: [], kanji: ['奥さん'] }, english: { main: ['someone’s wife'], other: [] } },
  { japanese: { main: ['おくる'], other: [], kanji: ['送る'] }, english: { main: ['to send'], other: [] } },
  { japanese: { main: ['おさけ'], other: [], kanji: ['お酒'] }, english: { main: ['alcohol'], other: ['sake'] } },
  { japanese: { main: ['おさら'], other: [], kanji: ['お皿'] }, english: { main: ['plate'], other: [] } },
  { japanese: { main: ['おじさん'], other: [], kanji: ['伯父さん'] }, english: { main: ['uncle'], other: [] } },
  { japanese: { main: ['おじいさん'], other: [], kanji: [] }, english: { main: ['grand father'], other: [] } },
  { japanese: { main: ['おす'], other: [], kanji: ['押す'] }, english: { main: ['to push'], other: [] } },
  { japanese: { main: ['おそい'], other: [], kanji: ['遅い'] }, english: { main: ['late'], other: ['slow'] } },
  { japanese: { main: ['おちゃ'], other: [], kanji: ['お茶'] }, english: { main: ['tea'], other: [] } },
  {
    japanese: { main: ['おてあらい'], other: [], kanji: ['お手洗い'] },
    english: { main: ['toilet'], other: ['lavatory'] },
  },
  { japanese: { main: ['おとうさん'], other: [], kanji: ['お父さん'] }, english: { main: ['father'], other: [] } },
  {
    japanese: { main: ['おとうと'], other: [], kanji: ['弟'] },
    english: { main: ['someone’s younger brother'], other: [] },
  },
  { japanese: { main: ['おとこ'], other: [], kanji: ['男'] }, english: { main: ['man'], other: [] } },
  { japanese: { main: ['おとこのこ'], other: [], kanji: ['男の子'] }, english: { main: ['boy'], other: [] } },
  {
    japanese: { main: ['おととい'], other: [], kanji: ['一昨日'] },
    english: { main: ['the day before yesterday'], other: [] },
  },
  {
    japanese: { main: ['おととし'], other: [], kanji: ['一昨年'] },
    english: { main: ['the year before last'], other: [] },
  },
  { japanese: { main: ['おとな'], other: [], kanji: ['大人'] }, english: { main: ['adult'], other: [] } },
  { japanese: { main: ['おなか'], other: [], kanji: ['お腹'] }, english: { main: ['stomach'], other: [] } },
  { japanese: { main: ['おなじ'], other: [], kanji: ['同じ'] }, english: { main: ['same'], other: [] } },
  {
    japanese: { main: ['おにいさん'], other: [], kanji: ['お兄さん'] },
    english: { main: ['someone’s elder brother'], other: [] },
  },
  {
    japanese: { main: ['おねえさん'], other: [], kanji: ['お姉さん'] },
    english: { main: ['someone’s elder sister'], other: [] },
  },
  { japanese: { main: ['おばさん'], other: [], kanji: ['伯母さん'] }, english: { main: ['aunt'], other: [] } },
  { japanese: { main: ['おばあさん'], other: [], kanji: [] }, english: { main: ['grandmother'], other: [] } },
  { japanese: { main: ['おべんとう'], other: [], kanji: ['お弁当'] }, english: { main: ['lunchbox'], other: [] } },
  {
    japanese: { main: ['おぼえる'], other: [], kanji: ['覚える'] },
    english: { main: ['to memorize'], other: ['to remember'] },
  },
  { japanese: { main: ['おもい'], other: [], kanji: ['重い'] }, english: { main: ['heavy'], other: [] } },
  {
    japanese: { main: ['おもしろい'], other: [], kanji: ['面白い'] },
    english: { main: ['interesting'], other: ['funny'] },
  },
  { japanese: { main: ['およぐ'], other: [], kanji: ['泳ぐ'] }, english: { main: ['to swim'], other: [] } },
  { japanese: { main: ['おりる'], other: [], kanji: ['降りる'] }, english: { main: ['to get off'], other: [] } },
  { japanese: { main: ['おわる'], other: [], kanji: ['終わる'] }, english: { main: ['to end'], other: [] } },
  { japanese: { main: ['おんがく'], other: [], kanji: ['音楽'] }, english: { main: ['music'], other: [] } },
  { japanese: { main: ['おんな'], other: [], kanji: ['女'] }, english: { main: ['woman'], other: [] } },
  { japanese: { main: ['おんなのこ'], other: [], kanji: ['女の子'] }, english: { main: ['girl'], other: [] } },
  { japanese: { main: ['〜かい'], other: [], kanji: ['〜回'] }, english: { main: ['~times'], other: [] } },
  { japanese: { main: ['〜かい'], other: [], kanji: ['〜階'] }, english: { main: ['~floor'], other: [] } },
  { japanese: { main: ['がいこく'], other: [], kanji: ['外国'] }, english: { main: ['foreign country'], other: [] } },
  { japanese: { main: ['がいこくじん'], other: [], kanji: ['外国人'] }, english: { main: ['foreigner'], other: [] } },
  {
    japanese: { main: ['かいしゃ'], other: [], kanji: ['会社'] },
    english: { main: ['company'], other: ['enterprise'] },
  },
  { japanese: { main: ['かいだん'], other: [], kanji: ['階段'] }, english: { main: ['stairs'], other: [] } },
  { japanese: { main: ['かいもの'], other: [], kanji: ['買物'] }, english: { main: ['shopping'], other: [] } },
  { japanese: { main: ['かう'], other: [], kanji: ['買う'] }, english: { main: ['to buy'], other: [] } },
  { japanese: { main: ['かえす'], other: [], kanji: ['返す'] }, english: { main: ['to return an object'], other: [] } },
  { japanese: { main: ['かえる'], other: [], kanji: ['帰る'] }, english: { main: ['to return home'], other: [] } },
  { japanese: { main: ['かお'], other: [], kanji: ['顔'] }, english: { main: ['face'], other: [] } },
  { japanese: { main: ['かかる'], other: [], kanji: [] }, english: { main: ['to take time'], other: ['money'] } },
  { japanese: { main: ['かぎ'], other: [], kanji: ['鍵'] }, english: { main: ['key'], other: [] } },
  { japanese: { main: ['かく'], other: [], kanji: ['書く'] }, english: { main: ['to write'], other: [] } },
  { japanese: { main: ['がくせい'], other: [], kanji: ['学生'] }, english: { main: ['student'], other: [] } },
  {
    japanese: { main: ['〜かげつ'], other: [], kanji: ['〜か月'] },
    english: { main: ['~ number of months'], other: [] },
  },
  { japanese: { main: ['かける'], other: [], kanji: [] }, english: { main: ['to wear'], other: [] } },
  { japanese: { main: ['かける'], other: [], kanji: [] }, english: { main: ['to make a phone call'], other: [] } },
  { japanese: { main: ['かさ'], other: [], kanji: ['傘'] }, english: { main: ['umbrella'], other: [] } },
  { japanese: { main: ['かす'], other: [], kanji: ['貸す'] }, english: { main: ['to lend'], other: [] } },
  { japanese: { main: ['かぜ'], other: [], kanji: ['風'] }, english: { main: ['wind'], other: [] } },
  { japanese: { main: ['かぜ'], other: [], kanji: ['風邪'] }, english: { main: ['a cold'], other: [] } },
  { japanese: { main: ['かぞく'], other: [], kanji: ['家族'] }, english: { main: ['family'], other: [] } },
  { japanese: { main: ['かた'], other: [], kanji: ['方'] }, english: { main: ['person (polite)'], other: [] } },
  { japanese: { main: ['かたかな'], other: [], kanji: ['片仮名'] }, english: { main: ['Katakana'], other: [] } },
  { japanese: { main: ['いちがつ'], other: [], kanji: ['一月'] }, english: { main: ['January'], other: [] } },
  { japanese: { main: ['にがつ'], other: [], kanji: ['二月'] }, english: { main: ['February'], other: [] } },
  { japanese: { main: ['さんがつ'], other: [], kanji: ['三月'] }, english: { main: ['March'], other: [] } },
  { japanese: { main: ['しがつ'], other: [], kanji: ['四月'] }, english: { main: ['April'], other: [] } },
  { japanese: { main: ['ごがつ'], other: [], kanji: ['五月'] }, english: { main: ['May'], other: [] } },
  { japanese: { main: ['ろくがつ'], other: [], kanji: ['六月'] }, english: { main: ['June'], other: [] } },
  { japanese: { main: ['しちがつ'], other: [], kanji: ['七月'] }, english: { main: ['July'], other: [] } },
  { japanese: { main: ['はちがつ'], other: [], kanji: ['八月'] }, english: { main: ['August'], other: [] } },
  { japanese: { main: ['くがつ'], other: [], kanji: ['九月'] }, english: { main: ['September'], other: [] } },
  { japanese: { main: ['じゅうがつ'], other: [], kanji: ['十月'] }, english: { main: ['October'], other: [] } },
  { japanese: { main: ['じゅういちがつ'], other: [], kanji: ['十一月'] }, english: { main: ['November'], other: [] } },
  { japanese: { main: ['じゅうにがつ'], other: [], kanji: ['十二月'] }, english: { main: ['December'], other: [] } },
  { japanese: { main: ['がっこう'], other: [], kanji: ['学校'] }, english: { main: ['school'], other: [] } },
  { japanese: { main: ['かど'], other: [], kanji: ['角'] }, english: { main: ['corner'], other: [] } },
  { japanese: { main: ['かない'], other: [], kanji: ['家内'] }, english: { main: ['my wife'], other: [] } },
  { japanese: { main: ['かばん'], other: [], kanji: ['鞄'] }, english: { main: ['bag'], other: [] } },
  { japanese: { main: ['かびん'], other: [], kanji: ['花瓶'] }, english: { main: ['vase'], other: [] } },
  { japanese: { main: ['かぶる'], other: [], kanji: ['冠る'] }, english: { main: ['to put on a hat'], other: [] } },
  { japanese: { main: ['かみ'], other: [], kanji: ['紙'] }, english: { main: ['paper'], other: [] } },
  { japanese: { main: ['かめら'], other: [], kanji: [] }, english: { main: ['camera'], other: [] } },
  { japanese: { main: ['かようび'], other: [], kanji: ['火曜日'] }, english: { main: ['Tuesday'], other: [] } },
  { japanese: { main: ['からい'], other: [], kanji: ['辛い'] }, english: { main: ['hot'], other: ['spicy'] } },
  { japanese: { main: ['からだ'], other: [], kanji: ['体'] }, english: { main: ['body'], other: [] } },
  { japanese: { main: ['かりる'], other: [], kanji: ['借りる'] }, english: { main: ['to borrow'], other: [] } },
  { japanese: { main: ['〜がります'], other: [], kanji: [] }, english: { main: ['3rd person wants to'], other: [] } },
  { japanese: { main: ['かるい'], other: [], kanji: ['軽い'] }, english: { main: ['light (not heavy)'], other: [] } },
  { japanese: { main: ['カレンダー'], other: [], kanji: [] }, english: { main: ['calendar'], other: [] } },
  { japanese: { main: ['かわ'], other: [], kanji: ['川'] }, english: { main: ['river'], other: [] } },
  { japanese: { main: ['~がわ'], other: [], kanji: ['〜側'] }, english: { main: ['~side'], other: [] } },
  { japanese: { main: ['かわいい'], other: [], kanji: ['可愛い'] }, english: { main: ['cute'], other: ['pretty'] } },
  { japanese: { main: ['かんじ'], other: [], kanji: ['漢字'] }, english: { main: ['Kanji character'], other: [] } },
  { japanese: { main: ['き'], other: [], kanji: ['木'] }, english: { main: ['tree'], other: [] } },
  { japanese: { main: ['きいろい'], other: [], kanji: ['黄色い'] }, english: { main: ['yellow'], other: [] } },
  {
    japanese: { main: ['きえる'], other: [], kanji: ['消える'] },
    english: { main: ['to go out'], other: ['to vanish'] },
  },
  {
    japanese: { main: ['きく'], other: [], kanji: ['聞く'] },
    english: { main: ['to hear'], other: ['to listen', ' to ask'] },
  },
  { japanese: { main: ['きた'], other: [], kanji: ['北'] }, english: { main: ['north'], other: [] } },
  { japanese: { main: ['ギター'], other: [], kanji: [] }, english: { main: ['guitar'], other: [] } },
  { japanese: { main: ['きたない'], other: [], kanji: ['汚い'] }, english: { main: ['dirty'], other: [] } },
  { japanese: { main: ['きっさてん'], other: [], kanji: ['喫茶店'] }, english: { main: ['coffee shop'], other: [] } },
  { japanese: { main: ['きって'], other: [], kanji: ['切手'] }, english: { main: ['stamp'], other: [] } },
  { japanese: { main: ['きっぷ'], other: [], kanji: ['切符'] }, english: { main: ['ticket'], other: [] } },
  { japanese: { main: ['きのう'], other: [], kanji: ['昨日'] }, english: { main: ['yesterday'], other: [] } },
  { japanese: { main: ['きゅう'], other: [], kanji: ['九'] }, english: { main: ['nine'], other: [] } },
  { japanese: { main: ['ぎゅうにく'], other: [], kanji: ['牛肉'] }, english: { main: ['beef'], other: [] } },
  { japanese: { main: ['ぎゅうにゅう'], other: [], kanji: ['牛乳'] }, english: { main: ['milk'], other: [] } },
  { japanese: { main: ['きょう'], other: [], kanji: ['今日'] }, english: { main: ['today'], other: [] } },
  { japanese: { main: ['きょうしつ'], other: [], kanji: ['教室'] }, english: { main: ['class room'], other: [] } },
  { japanese: { main: ['きょうだい'], other: [], kanji: ['兄弟'] }, english: { main: ['siblings'], other: [] } },
  { japanese: { main: ['きょねん'], other: [], kanji: ['去年'] }, english: { main: ['last year'], other: [] } },
  {
    japanese: { main: ['きらい'], other: [], kanji: ['嫌い'] },
    english: { main: ['unpleasant'], other: ['not likable'] },
  },
  { japanese: { main: ['きる'], other: [], kanji: ['切る'] }, english: { main: ['to cut'], other: [] } },
  { japanese: { main: ['きる'], other: [], kanji: ['着る'] }, english: { main: ['to wear'], other: ['to put on'] } },
  { japanese: { main: ['くる'], other: [], kanji: ['来る'] }, english: { main: ['to come'], other: [] } },
  { japanese: { main: ['きれい'], other: [], kanji: [] }, english: { main: ['beautiful'], other: ['clean'] } },
  { japanese: { main: ['キロ'], other: [], kanji: [] }, english: { main: ['kg'], other: [] } },
  { japanese: { main: ['キロ'], other: [], kanji: [] }, english: { main: ['km'], other: [] } },
  { japanese: { main: ['ぎんこう'], other: [], kanji: ['銀行'] }, english: { main: ['bank'], other: [] } },
  { japanese: { main: ['きんようび'], other: [], kanji: ['金曜日'] }, english: { main: ['Friday'], other: [] } },
  { japanese: { main: ['く'], other: [], kanji: ['九'] }, english: { main: ['nine'], other: [] } },
  { japanese: { main: ['くすり'], other: [], kanji: ['薬'] }, english: { main: ['medicine'], other: [] } },
  { japanese: { main: ['ください'], other: [], kanji: ['下さい'] }, english: { main: ['give me…'], other: [] } },
  { japanese: { main: ['くだもの'], other: [], kanji: ['果物'] }, english: { main: ['fruit'], other: [] } },
  { japanese: { main: ['くち'], other: [], kanji: ['口'] }, english: { main: ['mouth'], other: [] } },
  { japanese: { main: ['くつ'], other: [], kanji: ['靴'] }, english: { main: ['shoe'], other: [] } },
  { japanese: { main: ['くつした'], other: [], kanji: ['靴下'] }, english: { main: ['socks'], other: [] } },
  { japanese: { main: ['くに'], other: [], kanji: ['国'] }, english: { main: ['country'], other: [] } },
  { japanese: { main: ['くもり'], other: [], kanji: ['曇り'] }, english: { main: ['cloudy weather'], other: [] } },
  { japanese: { main: ['くらい'], other: [], kanji: ['暗い'] }, english: { main: ['dark'], other: [] } },
  { japanese: { main: ['ぐらい'], other: [], kanji: [] }, english: { main: ['about'], other: [] } },
  { japanese: { main: ['クラス'], other: [], kanji: [] }, english: { main: ['class'], other: [] } },
  { japanese: { main: ['グラム'], other: [], kanji: [] }, english: { main: ['gram'], other: [] } },
  { japanese: { main: ['くるま'], other: [], kanji: ['車'] }, english: { main: ['car'], other: [] } },
  { japanese: { main: ['くろい'], other: [], kanji: ['黒い'] }, english: { main: ['black'], other: [] } },
  { japanese: { main: ['けさ'], other: [], kanji: ['今朝'] }, english: { main: ['this morning'], other: [] } },
  {
    japanese: { main: ['けす'], other: [], kanji: ['消す'] },
    english: { main: ['to turn off'], other: ['switch off'] },
  },
  { japanese: { main: ['けっこう'], other: [], kanji: [] }, english: { main: ['fine'], other: ['all right'] } },
  { japanese: { main: ['けっこん'], other: [], kanji: ['結婚'] }, english: { main: ['marriage'], other: [] } },
  { japanese: { main: ['げつようび'], other: [], kanji: ['月曜日'] }, english: { main: ['Monday'], other: [] } },
  {
    japanese: { main: ['げんかん'], other: [], kanji: ['玄関'] },
    english: { main: ['entrance of a house'], other: [] },
  },
  {
    japanese: { main: ['げんき'], other: [], kanji: ['元気'] },
    english: { main: ['vigor'], other: ['health', ' vitality'] },
  },
  {
    japanese: { main: ['〜こ'], other: [], kanji: ['〜個'] },
    english: { main: ['counter for small objects'], other: [] },
  },
  { japanese: { main: ['ご'], other: [], kanji: ['五'] }, english: { main: ['five'], other: [] } },
  { japanese: { main: ['〜ご'], other: [], kanji: ['〜語'] }, english: { main: ['~ language'], other: [] } },
  {
    japanese: { main: ['こうえん'], other: [], kanji: ['公園'] },
    english: { main: ['park'], other: ['large garden'] },
  },
  { japanese: { main: ['こうばん'], other: [], kanji: ['交番'] }, english: { main: ['police box'], other: [] } },
  { japanese: { main: ['こえ'], other: [], kanji: ['声'] }, english: { main: ['voice'], other: [] } },
  { japanese: { main: ['コート'], other: [], kanji: [] }, english: { main: ['coat'], other: [] } },
  { japanese: { main: ['ここ'], other: [], kanji: [] }, english: { main: ['here'], other: [] } },
  { japanese: { main: ['ごご'], other: [], kanji: ['午後'] }, english: { main: ['afternoon'], other: [] } },
  {
    japanese: { main: ['ここのか'], other: [], kanji: ['九日'] },
    english: { main: ['9th day of a month'], other: ['9 days'] },
  },
  { japanese: { main: ['ここのつ'], other: [], kanji: ['九つ'] }, english: { main: ['nine'], other: [] } },
  {
    japanese: { main: ['ごしゅじん'], other: [], kanji: ['ご主人'] },
    english: { main: ['someone else’s husband'], other: [] },
  },
  { japanese: { main: ['ごぜん'], other: [], kanji: ['午前'] }, english: { main: ['morning'], other: ['a.m.'] } },
  { japanese: { main: ['こたえる'], other: [], kanji: ['答える'] }, english: { main: ['to answer'], other: [] } },
  { japanese: { main: ['こちら'], other: [], kanji: [] }, english: { main: ['this side'], other: ['this place'] } },
  { japanese: { main: ['コップ'], other: [], kanji: [] }, english: { main: ['cup'], other: ['glass'] } },
  { japanese: { main: ['ことし'], other: [], kanji: ['今年'] }, english: { main: ['this year'], other: [] } },
  { japanese: { main: ['ことば'], other: [], kanji: ['言葉'] }, english: { main: ['phrase'], other: ['language'] } },
  { japanese: { main: ['こども'], other: [], kanji: ['子供'] }, english: { main: ['child'], other: [] } },
  { japanese: { main: ['この'], other: [], kanji: [] }, english: { main: ['this…'], other: [] } },
  { japanese: { main: ['ごはん'], other: [], kanji: ['御飯'] }, english: { main: ['meal'], other: ['cooked rice'] } },
  { japanese: { main: ['こまる'], other: [], kanji: ['困る'] }, english: { main: ['to be in trouble'], other: [] } },
  { japanese: { main: ['これ'], other: [], kanji: [] }, english: { main: ['this'], other: [] } },
  { japanese: { main: ['ごろ'], other: [], kanji: [] }, english: { main: ['around…'], other: [] } },
  { japanese: { main: ['こんげつ'], other: [], kanji: ['今月'] }, english: { main: ['this month'], other: [] } },
  { japanese: { main: ['こんしゅう'], other: [], kanji: ['今週'] }, english: { main: ['this week'], other: [] } },
  {
    japanese: { main: ['こんな'], other: [], kanji: [] },
    english: { main: ['this sort of'], other: ['this kind of'] },
  },
  { japanese: { main: ['こんばん'], other: [], kanji: ['今晩'] }, english: { main: ['this evening'], other: [] } },
  { japanese: { main: ['さあ'], other: [], kanji: [] }, english: { main: ['well…'], other: [] } },
  { japanese: { main: ['〜さい'], other: [], kanji: ['〜歳'] }, english: { main: ['years old'], other: [] } },
  { japanese: { main: ['さかな'], other: [], kanji: ['魚'] }, english: { main: ['fish'], other: [] } },
  { japanese: { main: ['さき'], other: [], kanji: ['先'] }, english: { main: ['earlier'], other: ['former'] } },
  { japanese: { main: ['さく'], other: [], kanji: ['咲く'] }, english: { main: ['to blossom'], other: [] } },
  { japanese: { main: ['さくぶん'], other: [], kanji: ['作文'] }, english: { main: ['composition'], other: [] } },
  { japanese: { main: ['さす'], other: [], kanji: [] }, english: { main: ['to open an umbrella'], other: [] } },
  { japanese: { main: ['〜さつ'], other: [], kanji: ['冊'] }, english: { main: ['counter for books'], other: [] } },
  { japanese: { main: ['ざっし'], other: [], kanji: ['雑誌'] }, english: { main: ['magazine'], other: [] } },
  { japanese: { main: ['さとう'], other: [], kanji: ['砂糖'] }, english: { main: ['sugar'], other: [] } },
  { japanese: { main: ['さむい'], other: [], kanji: ['寒い'] }, english: { main: ['cold'], other: [] } },
  {
    japanese: { main: ['さらいねん'], other: [], kanji: ['再来年'] },
    english: { main: ['the year after next year'], other: [] },
  },
  { japanese: { main: ['さん'], other: [], kanji: ['三'] }, english: { main: ['three'], other: [] } },
  { japanese: { main: ['〜さん'], other: [], kanji: [] }, english: { main: ['Mr.'], other: ['Mrs.'] } },
  { japanese: { main: ['さんぽ'], other: [], kanji: ['散歩'] }, english: { main: ['to take a walk'], other: [] } },
  { japanese: { main: ['し'], other: [], kanji: ['四'] }, english: { main: ['four'], other: [] } },
  { japanese: { main: ['〜じ'], other: [], kanji: ['〜時'] }, english: { main: ['o’clock'], other: [] } },
  { japanese: { main: ['しお'], other: [], kanji: ['塩'] }, english: { main: ['salt'], other: [] } },
  { japanese: { main: ['しかし'], other: [], kanji: [] }, english: { main: ['however'], other: ['but'] } },
  { japanese: { main: ['じかん'], other: [], kanji: ['時間'] }, english: { main: ['time'], other: [] } },
  {
    japanese: { main: ['〜じかん'], other: [], kanji: ['〜時間'] },
    english: { main: ['~hours (classificator)'], other: [] },
  },
  { japanese: { main: ['しごと'], other: [], kanji: ['仕事'] }, english: { main: ['work'], other: [] } },
  { japanese: { main: ['じしょ'], other: [], kanji: ['辞書'] }, english: { main: ['dictionary'], other: [] } },
  { japanese: { main: ['しずか'], other: [], kanji: ['静か'] }, english: { main: ['quiet'], other: [] } },
  { japanese: { main: ['した'], other: [], kanji: ['下'] }, english: { main: ['under'], other: ['below'] } },
  { japanese: { main: ['しつもん'], other: [], kanji: ['質問'] }, english: { main: ['question'], other: [] } },
  { japanese: { main: ['じてんしゃ'], other: [], kanji: ['自転車'] }, english: { main: ['bicycle'], other: [] } },
  { japanese: { main: ['じどうしゃ'], other: [], kanji: ['自動車'] }, english: { main: ['car'], other: ['vehicle'] } },
  { japanese: { main: ['しぬ'], other: [], kanji: ['死ぬ'] }, english: { main: ['to die'], other: ['to pas away'] } },
  { japanese: { main: ['じびき'], other: [], kanji: ['字引'] }, english: { main: ['dictionary'], other: [] } },
  { japanese: { main: ['じぶん'], other: [], kanji: ['自分'] }, english: { main: ['oneself'], other: [] } },
  { japanese: { main: ['しまる'], other: [], kanji: ['閉まる'] }, english: { main: ['to close'], other: [] } },
  { japanese: { main: ['しめる'], other: [], kanji: ['閉める'] }, english: { main: ['to close'], other: [] } },
  {
    japanese: { main: ['しめる'], other: [], kanji: ['締める'] },
    english: { main: ['to fasten a seatbelt'], other: [] },
  },
  { japanese: { main: ['じゃ'], other: [], kanji: [] }, english: { main: ['well'], other: ['then'] } },
  { japanese: { main: ['しゃしん'], other: [], kanji: ['写真'] }, english: { main: ['photo'], other: [] } },
  { japanese: { main: ['シャツ'], other: [], kanji: [] }, english: { main: ['shirt'], other: [] } },
  { japanese: { main: ['じゅう'], other: [], kanji: ['十'] }, english: { main: ['ten'], other: [] } },
  { japanese: { main: ['〜しゅうかん'], other: [], kanji: ['~週間'] }, english: { main: ['… weeks'], other: [] } },
  { japanese: { main: ['じゅぎょう'], other: [], kanji: ['授業'] }, english: { main: ['lesson'], other: ['class'] } },
  { japanese: { main: ['しゅくだい'], other: [], kanji: ['宿題'] }, english: { main: ['homework'], other: [] } },
  {
    japanese: { main: ['じょうず'], other: [], kanji: ['上手'] },
    english: { main: ['to be good at something'], other: [] },
  },
  {
    japanese: { main: ['じょうぶ'], other: [], kanji: ['丈夫'] },
    english: { main: ['to be strong'], other: ['durable'] },
  },
  { japanese: { main: ['しょうゆ'], other: [], kanji: ['醤油'] }, english: { main: ['soy sauce'], other: [] } },
  {
    japanese: { main: ['しょくどう'], other: [], kanji: ['食堂'] },
    english: { main: ['dining room'], other: ['canteen'] },
  },
  { japanese: { main: ['しる'], other: [], kanji: ['知る'] }, english: { main: ['to know'], other: [] } },
  { japanese: { main: ['しろい'], other: [], kanji: ['白い'] }, english: { main: ['white'], other: [] } },
  {
    japanese: { main: ['〜じん'], other: [], kanji: ['〜人'] },
    english: { main: ['~an'], other: ['~ese (nationality)'] },
  },
  { japanese: { main: ['しんぶん'], other: [], kanji: ['新聞'] }, english: { main: ['newspaper'], other: [] } },
  { japanese: { main: ['すいようび'], other: [], kanji: ['水曜日'] }, english: { main: ['Wednesday'], other: [] } },
  { japanese: { main: ['すう'], other: [], kanji: ['吸う'] }, english: { main: ['to breathe'], other: ['to smoke'] } },
  { japanese: { main: ['スカート'], other: [], kanji: [] }, english: { main: ['skirt'], other: [] } },
  { japanese: { main: ['すき'], other: [], kanji: ['好き'] }, english: { main: ['to like'], other: [] } },
  { japanese: { main: ['〜すぎ'], other: [], kanji: ['〜過ぎ'] }, english: { main: ['past'], other: ['over'] } },
  { japanese: { main: ['すぐに'], other: [], kanji: [] }, english: { main: ['at once'], other: [] } },
  { japanese: { main: ['すこし'], other: [], kanji: ['少し'] }, english: { main: ['a little'], other: [] } },
  { japanese: { main: ['すずしい'], other: [], kanji: ['涼しい'] }, english: { main: ['cool'], other: [] } },
  { japanese: { main: ['〜ずつ'], other: [], kanji: [] }, english: { main: ['each'], other: [] } },
  { japanese: { main: ['ストーブ'], other: [], kanji: [] }, english: { main: ['stove'], other: ['heater'] } },
  { japanese: { main: ['スプーン'], other: [], kanji: [] }, english: { main: ['spoon'], other: [] } },
  { japanese: { main: ['スポーツ'], other: [], kanji: [] }, english: { main: ['sports'], other: [] } },
  { japanese: { main: ['ズボン'], other: [], kanji: [] }, english: { main: ['trousers'], other: [] } },
  {
    japanese: { main: ['すむ'], other: [], kanji: ['住む'] },
    english: { main: ['to live'], other: ['to reside somewhere'] },
  },
  { japanese: { main: ['スリッパ'], other: [], kanji: [] }, english: { main: ['slipper'], other: [] } },
  { japanese: { main: ['する'], other: [], kanji: [] }, english: { main: ['to do'], other: [] } },
  { japanese: { main: ['すわる'], other: [], kanji: ['座る'] }, english: { main: ['to sit'], other: [] } },
  { japanese: { main: ['せい'], other: [], kanji: ['背'] }, english: { main: ['height'], other: [] } },
  { japanese: { main: ['せいと'], other: [], kanji: ['生徒'] }, english: { main: ['student'], other: [] } },
  { japanese: { main: ['セーター'], other: [], kanji: [] }, english: { main: ['sweater'], other: [] } },
  { japanese: { main: ['せっけん'], other: [], kanji: ['石鹸'] }, english: { main: ['soap'], other: [] } },
  { japanese: { main: ['せびろ'], other: [], kanji: ['背広'] }, english: { main: ['jacket'], other: ['suit'] } },
  { japanese: { main: ['せまい'], other: [], kanji: ['狭い'] }, english: { main: ['narrow'], other: [] } },
  { japanese: { main: ['ゼロ'], other: [], kanji: [] }, english: { main: ['zero'], other: [] } },
  { japanese: { main: ['せん'], other: [], kanji: ['千'] }, english: { main: ['1'], other: ['0', ' thousand'] } },
  { japanese: { main: ['せんげつ'], other: [], kanji: ['先月'] }, english: { main: ['last month'], other: [] } },
  { japanese: { main: ['せんしゅう'], other: [], kanji: ['先週'] }, english: { main: ['last week'], other: [] } },
  { japanese: { main: ['せんせい'], other: [], kanji: ['先生'] }, english: { main: ['teacher'], other: [] } },
  { japanese: { main: ['せんたく'], other: [], kanji: ['洗濯'] }, english: { main: ['washing'], other: ['to wash'] } },
  { japanese: { main: ['ぜんぶ'], other: [], kanji: ['全部'] }, english: { main: ['all'], other: [] } },
  { japanese: { main: ['そう'], other: [], kanji: [] }, english: { main: ['so'], other: [] } },
  { japanese: { main: ['そうじ'], other: [], kanji: ['掃除'] }, english: { main: ['to clean'], other: [] } },
  { japanese: { main: ['そうして'], other: [], kanji: [] }, english: { main: ['and then'], other: [] } },
  { japanese: { main: ['そこ'], other: [], kanji: [] }, english: { main: ['there'], other: [] } },
  { japanese: { main: ['そちら'], other: [], kanji: [] }, english: { main: ['there (polite)'], other: [] } },
  { japanese: { main: ['そと'], other: [], kanji: ['外'] }, english: { main: ['outside'], other: [] } },
  { japanese: { main: ['その'], other: [], kanji: [] }, english: { main: ['that…'], other: [] } },
  { japanese: { main: ['そば'], other: [], kanji: [] }, english: { main: ['next to'], other: [] } },
  { japanese: { main: ['そら'], other: [], kanji: ['空'] }, english: { main: ['sky'], other: [] } },
  { japanese: { main: ['それ'], other: [], kanji: [] }, english: { main: ['that'], other: [] } },
  { japanese: { main: ['それから'], other: [], kanji: [] }, english: { main: ['after that'], other: [] } },
  { japanese: { main: ['それでは'], other: [], kanji: [] }, english: { main: ['then'], other: ['well'] } },
  {
    japanese: { main: ['〜だい'], other: [], kanji: ['〜台'] },
    english: { main: ['counter for machines'], other: [] },
  },
  { japanese: { main: ['だいがく'], other: [], kanji: ['大学'] }, english: { main: ['university'], other: [] } },
  { japanese: { main: ['たいしかん'], other: [], kanji: ['大使館'] }, english: { main: ['embassy'], other: [] } },
  { japanese: { main: ['だいじょうぶ'], other: [], kanji: ['大丈夫'] }, english: { main: ['OK'], other: [] } },
  {
    japanese: { main: ['だいすき'], other: [], kanji: ['大好き'] },
    english: { main: ['to be very fond of'], other: [] },
  },
  { japanese: { main: ['たいせつ'], other: [], kanji: ['大切'] }, english: { main: ['very important'], other: [] } },
  { japanese: { main: ['たいてい'], other: [], kanji: [] }, english: { main: ['mostly'], other: ['usually'] } },
  { japanese: { main: ['だいどころ'], other: [], kanji: ['台所'] }, english: { main: ['kitchen'], other: [] } },
  { japanese: { main: ['たいへん'], other: [], kanji: ['大変'] }, english: { main: ['very'], other: ['serious'] } },
  { japanese: { main: ['たかい'], other: [], kanji: ['高い'] }, english: { main: ['high'], other: ['expensive'] } },
  { japanese: { main: ['たくさん'], other: [], kanji: ['沢山'] }, english: { main: ['many'], other: ['much'] } },
  { japanese: { main: ['タクシー'], other: [], kanji: [] }, english: { main: ['taxi'], other: [] } },
  { japanese: { main: ['だす'], other: [], kanji: ['出す'] }, english: { main: ['to take out'], other: ['hand in'] } },
  {
    japanese: { main: ['〜たち'], other: [], kanji: ['~達'] },
    english: { main: ['more than one'], other: ['and others'] },
  },
  { japanese: { main: ['たつ'], other: [], kanji: ['立つ'] }, english: { main: ['to stand'], other: [] } },
  { japanese: { main: ['たてもの'], other: [], kanji: ['建物'] }, english: { main: ['building'], other: [] } },
  {
    japanese: { main: ['たのしい'], other: [], kanji: ['楽しい'] },
    english: { main: ['pleasant'], other: ['enjoyable'] },
  },
  { japanese: { main: ['たのむ'], other: [], kanji: ['頼む'] }, english: { main: ['to ask'], other: ['to request'] } },
  { japanese: { main: ['たばこ'], other: [], kanji: [] }, english: { main: ['cigarette'], other: [] } },
  { japanese: { main: ['たぶん'], other: [], kanji: ['多分'] }, english: { main: ['perhaps'], other: ['probably'] } },
  { japanese: { main: ['たべもの'], other: [], kanji: ['食べ物'] }, english: { main: ['food'], other: [] } },
  { japanese: { main: ['たべる'], other: [], kanji: ['食べる'] }, english: { main: ['to eat'], other: [] } },
  { japanese: { main: ['たまご'], other: [], kanji: ['卵'] }, english: { main: ['egg'], other: [] } },
  { japanese: { main: ['だれ'], other: [], kanji: ['誰'] }, english: { main: ['who?'], other: [] } },
  { japanese: { main: ['たんじょうび'], other: [], kanji: ['誕生日'] }, english: { main: ['birthday'], other: [] } },
  { japanese: { main: ['だんだん'], other: [], kanji: [] }, english: { main: ['gradually'], other: [] } },
  { japanese: { main: ['ちいさい'], other: [], kanji: ['小さい'] }, english: { main: ['small'], other: [] } },
  { japanese: { main: ['ちかい'], other: [], kanji: ['近い'] }, english: { main: ['near'], other: ['close'] } },
  { japanese: { main: ['ちがう'], other: [], kanji: ['違う'] }, english: { main: ['different'], other: [] } },
  { japanese: { main: ['ちかてつ'], other: [], kanji: ['地下鉄'] }, english: { main: ['subway'], other: [] } },
  { japanese: { main: ['ちず'], other: [], kanji: ['地図'] }, english: { main: ['map'], other: [] } },
  { japanese: { main: ['ちち'], other: [], kanji: ['父'] }, english: { main: ['my father'], other: [] } },
  { japanese: { main: ['ちゃいろ'], other: [], kanji: ['茶色'] }, english: { main: ['brown'], other: [] } },
  { japanese: { main: ['ちゃわん'], other: [], kanji: ['茶碗'] }, english: { main: ['rice bowl'], other: [] } },
  { japanese: { main: ['〜ちゅう'], other: [], kanji: ['〜中'] }, english: { main: ['in the middle of'], other: [] } },
  { japanese: { main: ['ちょうど'], other: [], kanji: [] }, english: { main: ['just'], other: [] } },
  { japanese: { main: ['ちょっと'], other: [], kanji: [] }, english: { main: ['a little'], other: [] } },
  {
    japanese: { main: ['ついたち'], other: [], kanji: ['一日'] },
    english: { main: ['the 1st day of a month'], other: [] },
  },
  { japanese: { main: ['つかう'], other: [], kanji: ['使う'] }, english: { main: ['to use'], other: [] } },
  { japanese: { main: ['つかれる'], other: [], kanji: ['疲れる'] }, english: { main: ['to get tired'], other: [] } },
  { japanese: { main: ['つぎ'], other: [], kanji: ['次'] }, english: { main: ['next'], other: [] } },
  { japanese: { main: ['つく'], other: [], kanji: ['着く'] }, english: { main: ['to arrive'], other: [] } },
  { japanese: { main: ['つくえ'], other: [], kanji: ['机'] }, english: { main: ['table'], other: [] } },
  { japanese: { main: ['つくる'], other: [], kanji: ['作る'] }, english: { main: ['to make'], other: ['to produce'] } },
  { japanese: { main: ['つける'], other: [], kanji: ['点ける'] }, english: { main: ['to turn on'], other: [] } },
  {
    japanese: { main: ['つとめる'], other: [], kanji: ['勤める'] },
    english: { main: ['to work for someone'], other: [] },
  },
  {
    japanese: { main: ['つまらない'], other: [], kanji: ['詰らない'] },
    english: { main: ['uninteresting'], other: [] },
  },
  { japanese: { main: ['つめたい'], other: [], kanji: ['冷たい'] }, english: { main: ['cold'], other: [] } },
  { japanese: { main: ['つよい'], other: [], kanji: ['強い'] }, english: { main: ['strong'], other: [] } },
  { japanese: { main: ['て'], other: [], kanji: ['手'] }, english: { main: ['hand'], other: [] } },
  { japanese: { main: ['テープ'], other: [], kanji: [] }, english: { main: ['tape'], other: [] } },
  { japanese: { main: ['テープレコーダー'], other: [], kanji: [] }, english: { main: ['tape recorder'], other: [] } },
  { japanese: { main: ['テーブル'], other: [], kanji: [] }, english: { main: ['table'], other: [] } },
  { japanese: { main: ['でかける'], other: [], kanji: ['出かける'] }, english: { main: ['to go out'], other: [] } },
  { japanese: { main: ['てがみ'], other: [], kanji: ['手紙'] }, english: { main: ['letter'], other: [] } },
  { japanese: { main: ['できる'], other: [], kanji: ['出来る'] }, english: { main: ['can'], other: [] } },
  { japanese: { main: ['でぐち'], other: [], kanji: ['出口'] }, english: { main: ['exit'], other: [] } },
  { japanese: { main: ['テスト'], other: [], kanji: [] }, english: { main: ['test'], other: [] } },
  { japanese: { main: ['では'], other: [], kanji: [] }, english: { main: ['then'], other: ['well'] } },
  { japanese: { main: ['デパート'], other: [], kanji: [] }, english: { main: ['department store'], other: [] } },
  { japanese: { main: ['でも'], other: [], kanji: [] }, english: { main: ['but'], other: [] } },
  { japanese: { main: ['でます'], other: [], kanji: ['出ます'] }, english: { main: ['to leave'], other: [] } },
  { japanese: { main: ['テレビ'], other: [], kanji: [] }, english: { main: ['TV'], other: [] } },
  { japanese: { main: ['てんき'], other: [], kanji: ['天気'] }, english: { main: ['weather'], other: [] } },
  { japanese: { main: ['でんき'], other: [], kanji: ['電気'] }, english: { main: ['electricity'], other: [] } },
  { japanese: { main: ['でんしゃ'], other: [], kanji: ['電車'] }, english: { main: ['train'], other: [] } },
  { japanese: { main: ['でんわ'], other: [], kanji: ['電話'] }, english: { main: ['phone'], other: [] } },
  { japanese: { main: ['と'], other: [], kanji: ['戸'] }, english: { main: ['door'], other: [] } },
  { japanese: { main: ['〜ど'], other: [], kanji: ['〜度'] }, english: { main: ['~times'], other: ['~degree'] } },
  { japanese: { main: ['ドア'], other: [], kanji: [] }, english: { main: ['door'], other: [] } },
  { japanese: { main: ['トイレ'], other: [], kanji: [] }, english: { main: ['toilet'], other: ['lavatory'] } },
  { japanese: { main: ['どう'], other: [], kanji: [] }, english: { main: ['how?'], other: [] } },
  { japanese: { main: ['どうして'], other: [], kanji: [] }, english: { main: ['why?'], other: [] } },
  { japanese: { main: ['どうぞ'], other: [], kanji: [] }, english: { main: ['please'], other: ['here you are'] } },
  { japanese: { main: ['どうぶつ'], other: [], kanji: ['動物'] }, english: { main: ['animal'], other: [] } },
  { japanese: { main: ['どうも'], other: [], kanji: [] }, english: { main: ['thanks'], other: [] } },
  { japanese: { main: ['とお'], other: [], kanji: ['十'] }, english: { main: ['ten'], other: [] } },
  { japanese: { main: ['とおい'], other: [], kanji: ['遠い'] }, english: { main: ['far'], other: [] } },
  {
    japanese: { main: ['とおか'], other: [], kanji: ['十日'] },
    english: { main: ['the 10th day of a month'], other: ['10 days'] },
  },
  { japanese: { main: ['ときどき'], other: [], kanji: ['時々'] }, english: { main: ['sometimes'], other: [] } },
  {
    japanese: { main: ['とけい'], other: ['うでどけい'], kanji: ['時計'] },
    english: { main: ['watch'], other: ['clock'] },
  },
  { japanese: { main: ['どこ'], other: [], kanji: [] }, english: { main: ['where?'], other: [] } },
  { japanese: { main: ['ところ'], other: [], kanji: ['所'] }, english: { main: ['place'], other: [] } },
  { japanese: { main: ['としょかん'], other: [], kanji: ['図書館'] }, english: { main: ['library'], other: [] } },
  { japanese: { main: ['どちら'], other: [], kanji: [] }, english: { main: ['which'], other: ['where (polite)'] } },
  { japanese: { main: ['とても'], other: [], kanji: [] }, english: { main: ['very much'], other: ['quiet'] } },
  { japanese: { main: ['どなた'], other: [], kanji: [] }, english: { main: ['who (polite)'], other: [] } },
  { japanese: { main: ['となり'], other: [], kanji: ['隣り'] }, english: { main: ['next to'], other: [] } },
  { japanese: { main: ['どの'], other: [], kanji: [] }, english: { main: ['which?'], other: [] } },
  { japanese: { main: ['とぶ'], other: [], kanji: ['飛ぶ'] }, english: { main: ['to fly'], other: [] } },
  { japanese: { main: ['とまる'], other: [], kanji: ['止まる'] }, english: { main: ['to stop'], other: [] } },
  { japanese: { main: ['ともだち'], other: [], kanji: ['友達'] }, english: { main: ['friend'], other: [] } },
  { japanese: { main: ['どようび'], other: [], kanji: ['土曜日'] }, english: { main: ['Saturday'], other: [] } },
  { japanese: { main: ['とり'], other: [], kanji: ['鳥'] }, english: { main: ['bird'], other: [] } },
  { japanese: { main: ['とりにく'], other: [], kanji: ['鶏肉'] }, english: { main: ['chicken meat'], other: [] } },
  { japanese: { main: ['とる'], other: [], kanji: ['取る'] }, english: { main: ['to take'], other: [] } },
  { japanese: { main: ['とる'], other: [], kanji: ['撮る'] }, english: { main: ['to take a photo'], other: [] } },
  { japanese: { main: ['どれ'], other: [], kanji: [] }, english: { main: ['which?'], other: [] } },
  { japanese: { main: ['どんな'], other: [], kanji: [] }, english: { main: ['what kind of?'], other: [] } },
  { japanese: { main: ['ナイフ'], other: [], kanji: [] }, english: { main: ['knife'], other: [] } },
  { japanese: { main: ['なか'], other: [], kanji: ['中'] }, english: { main: ['inside'], other: [] } },
  { japanese: { main: ['ながい'], other: [], kanji: ['長い'] }, english: { main: ['long'], other: [] } },
  { japanese: { main: ['なく'], other: [], kanji: ['鳴く'] }, english: { main: ['to sing'], other: ['mew', ' moo'] } },
  { japanese: { main: ['なつ'], other: [], kanji: ['夏'] }, english: { main: ['summer'], other: [] } },
  {
    japanese: { main: ['なつやすみ'], other: [], kanji: ['夏休み'] },
    english: { main: ['summer vacation'], other: [] },
  },
  { japanese: { main: ['〜など'], other: [], kanji: [] }, english: { main: ['and so on'], other: [] } },
  { japanese: { main: ['ななつ'], other: [], kanji: ['七つ'] }, english: { main: ['seven'], other: [] } },
  { japanese: { main: ['なに'], other: [], kanji: ['何'] }, english: { main: ['what?'], other: [] } },
  {
    japanese: { main: ['なのか'], other: [], kanji: ['七日'] },
    english: { main: ['the 7th of a month'], other: ['7 days'] },
  },
  { japanese: { main: ['なまえ'], other: [], kanji: ['名前'] }, english: { main: ['name'], other: [] } },
  { japanese: { main: ['ならう'], other: [], kanji: ['習う'] }, english: { main: ['to learn'], other: [] } },
  { japanese: { main: ['ならぶ'], other: [], kanji: ['並ぶ'] }, english: { main: ['to form a line'], other: [] } },
  { japanese: { main: ['ならべる'], other: [], kanji: ['並べる'] }, english: { main: ['to line up'], other: [] } },
  { japanese: { main: ['なる'], other: [], kanji: [] }, english: { main: ['to become'], other: [] } },
  { japanese: { main: ['に'], other: [], kanji: ['二'] }, english: { main: ['two'], other: [] } },
  { japanese: { main: ['にぎやか'], other: [], kanji: ['賑やか'] }, english: { main: ['lively'], other: [] } },
  { japanese: { main: ['おにく'], other: [], kanji: ['お肉'] }, english: { main: ['meat'], other: [] } },
  { japanese: { main: ['にし'], other: [], kanji: ['西'] }, english: { main: ['west'], other: [] } },
  { japanese: { main: ['〜にち'], other: [], kanji: ['〜日'] }, english: { main: ['…st'], other: ['..nd', ' ..th'] } },
  { japanese: { main: ['にちようび'], other: [], kanji: ['日曜日'] }, english: { main: ['Sunday'], other: [] } },
  { japanese: { main: ['にもつ'], other: [], kanji: ['荷物'] }, english: { main: ['luggage'], other: [] } },
  { japanese: { main: ['ニュース'], other: [], kanji: [] }, english: { main: ['news'], other: [] } },
  { japanese: { main: ['にわ'], other: [], kanji: ['庭'] }, english: { main: ['garden'], other: [] } },
  { japanese: { main: ['~にん'], other: [], kanji: ['〜人'] }, english: { main: ['… people'], other: [] } },
  { japanese: { main: ['ぬぐ'], other: [], kanji: ['脱ぐ'] }, english: { main: ['to take off clothes'], other: [] } },
  { japanese: { main: ['ネクタイ'], other: [], kanji: [] }, english: { main: ['necktie'], other: [] } },
  { japanese: { main: ['ねる'], other: [], kanji: ['寝る'] }, english: { main: ['to go to bed'], other: [] } },
  { japanese: { main: ['〜ねん'], other: [], kanji: ['〜年'] }, english: { main: ['~years'], other: [] } },
  { japanese: { main: ['ノート'], other: [], kanji: [] }, english: { main: ['notebook'], other: [] } },
  { japanese: { main: ['のぼる'], other: [], kanji: ['登る'] }, english: { main: ['to climb up'], other: [] } },
  { japanese: { main: ['のみもの'], other: [], kanji: ['飲物'] }, english: { main: ['drinks'], other: [] } },
  { japanese: { main: ['のむ'], other: [], kanji: ['飲む'] }, english: { main: ['to drink'], other: [] } },
  { japanese: { main: ['のる'], other: [], kanji: ['乗る'] }, english: { main: ['to take'], other: ['to ride'] } },
  { japanese: { main: ['は'], other: [], kanji: ['歯'] }, english: { main: ['teeth'], other: [] } },
  { japanese: { main: ['パーテイー'], other: [], kanji: [] }, english: { main: ['party'], other: [] } },
  { japanese: { main: ['はい'], other: [], kanji: [] }, english: { main: ['yes'], other: [] } },
  { japanese: { main: ['〜はい'], other: [], kanji: [] }, english: { main: ['cups of ~'], other: [] } },
  { japanese: { main: ['はいざら'], other: [], kanji: ['灰皿'] }, english: { main: ['ashtray'], other: [] } },
  { japanese: { main: ['はいる'], other: [], kanji: ['入る'] }, english: { main: ['to enter'], other: [] } },
  { japanese: { main: ['はがき'], other: [], kanji: ['葉書'] }, english: { main: ['postcard'], other: [] } },
  { japanese: { main: ['はく'], other: [], kanji: ['履く'] }, english: { main: ['to put on shoes'], other: [] } },
  { japanese: { main: ['はこ'], other: [], kanji: ['箱'] }, english: { main: ['box'], other: [] } },
  { japanese: { main: ['はし'], other: [], kanji: ['橋'] }, english: { main: ['bridge'], other: [] } },
  { japanese: { main: ['はし'], other: [], kanji: ['箸'] }, english: { main: ['chopsticks'], other: [] } },
  {
    japanese: { main: ['はじまる'], other: [], kanji: ['始まる'] },
    english: { main: ['to begin'], other: ['to start'] },
  },
  {
    japanese: { main: ['はじめ'], other: [], kanji: ['始め'] },
    english: { main: ['start'], other: ['the beginning'] },
  },
  {
    japanese: { main: ['はじめて'], other: [], kanji: ['初めて'] },
    english: { main: ['for the first time'], other: [] },
  },
  { japanese: { main: ['はしる'], other: [], kanji: ['走る'] }, english: { main: ['to run'], other: [] } },
  { japanese: { main: ['バス'], other: [], kanji: [] }, english: { main: ['bus'], other: [] } },
  { japanese: { main: ['バター'], other: [], kanji: [] }, english: { main: ['butter'], other: [] } },
  { japanese: { main: ['はたち'], other: [], kanji: ['二十歳'] }, english: { main: ['20 years old'], other: [] } },
  { japanese: { main: ['はたらく'], other: [], kanji: ['働く'] }, english: { main: ['to work'], other: [] } },
  { japanese: { main: ['はち'], other: [], kanji: ['八'] }, english: { main: ['eight'], other: [] } },
  {
    japanese: { main: ['はつか'], other: [], kanji: ['二十日'] },
    english: { main: ['the 20th of the month'], other: ['20 days'] },
  },
  { japanese: { main: ['はな'], other: [], kanji: ['花'] }, english: { main: ['flower'], other: [] } },
  { japanese: { main: ['はな'], other: [], kanji: ['鼻'] }, english: { main: ['nose'], other: [] } },
  { japanese: { main: ['はなし'], other: [], kanji: ['話'] }, english: { main: ['conversation'], other: ['tale'] } },
  {
    japanese: { main: ['はなす'], other: [], kanji: ['話す'] },
    english: { main: ['to talk'], other: ['to speak', ' to tell'] },
  },
  { japanese: { main: ['はは'], other: [], kanji: ['母'] }, english: { main: ['my mother'], other: [] } },
  { japanese: { main: ['はやい'], other: [], kanji: ['早い'] }, english: { main: ['early'], other: [] } },
  { japanese: { main: ['はやい'], other: [], kanji: ['速い'] }, english: { main: ['fast'], other: ['quick'] } },
  { japanese: { main: ['はる'], other: [], kanji: ['春'] }, english: { main: ['spring'], other: [] } },
  {
    japanese: { main: ['はる'], other: [], kanji: ['張る'] },
    english: { main: ['to put something on'], other: ['to stick'] },
  },
  { japanese: { main: ['はれる'], other: [], kanji: ['晴れる'] }, english: { main: ['to clear up'], other: [] } },
  { japanese: { main: ['〜はん'], other: [], kanji: ['〜半'] }, english: { main: ['Half~'], other: [] } },
  { japanese: { main: ['ばん'], other: [], kanji: ['晩'] }, english: { main: ['evening'], other: [] } },
  { japanese: { main: ['〜ばん'], other: [], kanji: ['~番'] }, english: { main: ['No.~'], other: ['ranking'] } },
  { japanese: { main: ['パン'], other: [], kanji: [] }, english: { main: ['bread'], other: [] } },
  { japanese: { main: ['ハンカチ'], other: [], kanji: [] }, english: { main: ['handkerchief'], other: [] } },
  { japanese: { main: ['ばんごう'], other: [], kanji: ['番号'] }, english: { main: ['number'], other: [] } },
  { japanese: { main: ['ばんごはん'], other: [], kanji: ['晩ご飯'] }, english: { main: ['dinner'], other: [] } },
  { japanese: { main: ['はんぶん'], other: [], kanji: ['半分'] }, english: { main: ['half'], other: [] } },
  { japanese: { main: ['ひがし'], other: [], kanji: ['東'] }, english: { main: ['east'], other: [] } },
  { japanese: { main: ['〜ひき'], other: [], kanji: ['〜匹'] }, english: { main: ['counter for animals'], other: [] } },
  { japanese: { main: ['ひく'], other: [], kanji: ['引く'] }, english: { main: ['to pull'], other: [] } },
  {
    japanese: { main: ['ひく'], other: [], kanji: ['弾く'] },
    english: { main: ['to play (an instrument)'], other: [] },
  },
  { japanese: { main: ['ひくい'], other: [], kanji: ['低い'] }, english: { main: ['low'], other: [] } },
  { japanese: { main: ['ひこうき'], other: [], kanji: ['飛行機'] }, english: { main: ['plane'], other: [] } },
  { japanese: { main: ['ひだり'], other: [], kanji: ['左'] }, english: { main: ['left'], other: [] } },
  { japanese: { main: ['ひと'], other: [], kanji: ['人'] }, english: { main: ['person'], other: [] } },
  { japanese: { main: ['ひとつ'], other: [], kanji: ['一つ'] }, english: { main: ['one'], other: [] } },
  { japanese: { main: ['ひとつき'], other: [], kanji: ['一月'] }, english: { main: ['one month'], other: [] } },
  { japanese: { main: ['ひとり'], other: [], kanji: ['一人'] }, english: { main: ['one person'], other: [] } },
  { japanese: { main: ['ひま'], other: [], kanji: ['暇'] }, english: { main: ['free time'], other: ['leisure'] } },
  { japanese: { main: ['ひゃく'], other: [], kanji: ['百'] }, english: { main: ['hundred'], other: [] } },
  { japanese: { main: ['びょういん'], other: [], kanji: ['病院'] }, english: { main: ['hospital'], other: [] } },
  { japanese: { main: ['びょうき'], other: [], kanji: ['病気'] }, english: { main: ['ill'], other: ['sick'] } },
  {
    japanese: { main: ['ひらがな'], other: [], kanji: ['平仮名'] },
    english: { main: ['hiragana characters'], other: [] },
  },
  { japanese: { main: ['ひる'], other: [], kanji: ['昼'] }, english: { main: ['noon'], other: [] } },
  { japanese: { main: ['ひるごはん'], other: [], kanji: ['昼ご飯'] }, english: { main: ['lunch'], other: [] } },
  { japanese: { main: ['ひろい'], other: [], kanji: ['広い'] }, english: { main: ['wide'], other: ['spacious'] } },
  { japanese: { main: ['フィルム'], other: [], kanji: [] }, english: { main: ['film'], other: [] } },
  { japanese: { main: ['ふうとう'], other: [], kanji: ['封筒'] }, english: { main: ['envelope'], other: [] } },
  { japanese: { main: ['プール'], other: [], kanji: [] }, english: { main: ['pool'], other: [] } },
  { japanese: { main: ['フォーク'], other: [], kanji: [] }, english: { main: ['fork'], other: [] } },
  { japanese: { main: ['ふく'], other: [], kanji: ['吹く'] }, english: { main: ['to blow (wind)'], other: [] } },
  { japanese: { main: ['ふく'], other: [], kanji: ['服'] }, english: { main: ['clothes'], other: [] } },
  { japanese: { main: ['ふたつ'], other: [], kanji: ['二つ'] }, english: { main: ['two'], other: [] } },
  { japanese: { main: ['ぶたにく'], other: [], kanji: ['豚肉'] }, english: { main: ['pork'], other: [] } },
  { japanese: { main: ['ふたり'], other: [], kanji: ['二人'] }, english: { main: ['two people'], other: [] } },
  {
    japanese: { main: ['ふつか'], other: [], kanji: ['二日'] },
    english: { main: ['2nd day of the month'], other: ['2 days'] },
  },
  { japanese: { main: ['ふとい'], other: [], kanji: ['太い'] }, english: { main: ['thick'], other: ['fat'] } },
  { japanese: { main: ['ふる'], other: [], kanji: ['降る'] }, english: { main: ['to fall (rain'], other: ['snow)'] } },
  { japanese: { main: ['ふるい'], other: [], kanji: ['古い'] }, english: { main: ['old'], other: [] } },
  { japanese: { main: ['おふろ'], other: [], kanji: ['お風呂'] }, english: { main: ['bath'], other: [] } },
  { japanese: { main: ['〜ふん'], other: [], kanji: ['〜分'] }, english: { main: ['~minutes'], other: [] } },
  { japanese: { main: ['ページ'], other: [], kanji: [] }, english: { main: ['page'], other: [] } },
  { japanese: { main: ['へた'], other: [], kanji: ['下手'] }, english: { main: ['not good at something'], other: [] } },
  { japanese: { main: ['ベッド'], other: [], kanji: [] }, english: { main: ['bed'], other: [] } },
  { japanese: { main: ['へや'], other: [], kanji: ['部屋'] }, english: { main: ['room'], other: [] } },
  { japanese: { main: ['へん'], other: [], kanji: ['辺'] }, english: { main: ['side'], other: ['part', ' area'] } },
  { japanese: { main: ['ぺん'], other: [], kanji: [] }, english: { main: ['pen'], other: [] } },
  { japanese: { main: ['べんきょう'], other: [], kanji: ['勉強'] }, english: { main: ['to study'], other: [] } },
  { japanese: { main: ['べんり'], other: [], kanji: ['便利'] }, english: { main: ['convenient'], other: [] } },
  { japanese: { main: ['ほう'], other: [], kanji: ['方'] }, english: { main: ['~より〜のほうが〜'], other: [] } },
  { japanese: { main: ['ぼうし'], other: [], kanji: ['帽子'] }, english: { main: ['hat'], other: [] } },
  { japanese: { main: ['ボールペン'], other: [], kanji: [] }, english: { main: ['ballpen'], other: [] } },
  { japanese: { main: ['ほか'], other: [], kanji: ['他'] }, english: { main: ['another'], other: ['other'] } },
  { japanese: { main: ['ポケット'], other: [], kanji: [] }, english: { main: ['pocket'], other: [] } },
  { japanese: { main: ['ほしい'], other: [], kanji: ['欲しい'] }, english: { main: ['to want something'], other: [] } },
  { japanese: { main: ['ほそい'], other: [], kanji: ['細い'] }, english: { main: ['thin'], other: ['fine'] } },
  { japanese: { main: ['ボタン'], other: [], kanji: [] }, english: { main: ['button'], other: [] } },
  { japanese: { main: ['ホテル'], other: [], kanji: [] }, english: { main: ['hotel'], other: [] } },
  { japanese: { main: ['ほん'], other: [], kanji: ['本'] }, english: { main: ['book'], other: [] } },
  {
    japanese: { main: ['~ほん'], other: [], kanji: ['〜本'] },
    english: { main: ['counter for long objects'], other: [] },
  },
  { japanese: { main: ['ほんだな'], other: [], kanji: ['本棚'] }, english: { main: ['bookshelf'], other: [] } },
  { japanese: { main: ['ほんとうに'], other: [], kanji: ['本当に'] }, english: { main: ['really'], other: [] } },
  {
    japanese: { main: ['〜まい'], other: [], kanji: ['〜枚'] },
    english: { main: ['counter for thin objects'], other: [] },
  },
  { japanese: { main: ['まいあさ'], other: [], kanji: ['毎朝'] }, english: { main: ['every morning'], other: [] } },
  {
    japanese: { main: ['まいつき/まいげつ'], other: [], kanji: ['毎月'] },
    english: { main: ['every month'], other: [] },
  },
  { japanese: { main: ['まいしゅう'], other: [], kanji: ['毎週'] }, english: { main: ['every week'], other: [] } },
  { japanese: { main: ['まいにち'], other: [], kanji: ['毎日'] }, english: { main: ['every day'], other: [] } },
  {
    japanese: { main: ['まいとし/まいねん'], other: [], kanji: ['毎年'] },
    english: { main: ['every year'], other: [] },
  },
  { japanese: { main: ['まいばん'], other: [], kanji: ['毎晩'] }, english: { main: ['every evening'], other: [] } },
  { japanese: { main: ['まえ'], other: [], kanji: ['前'] }, english: { main: ['front'], other: [] } },
  { japanese: { main: ['〜まえ'], other: [], kanji: ['〜前'] }, english: { main: ['before'], other: ['in front of'] } },
  { japanese: { main: ['まがる'], other: [], kanji: ['曲がる'] }, english: { main: ['to turn'], other: [] } },
  { japanese: { main: ['まずい'], other: [], kanji: ['不味い'] }, english: { main: ['bad tasting'], other: [] } },
  { japanese: { main: ['また'], other: [], kanji: [] }, english: { main: ['also'], other: ['again'] } },
  { japanese: { main: ['まだ'], other: [], kanji: [] }, english: { main: ['not yet'], other: [] } },
  { japanese: { main: ['まち'], other: [], kanji: ['町'] }, english: { main: ['city'], other: ['town'] } },
  { japanese: { main: ['まつ'], other: [], kanji: ['待つ'] }, english: { main: ['to wait'], other: [] } },
  {
    japanese: { main: ['まっすぐに'], other: [], kanji: ['真直ぐに'] },
    english: { main: ['straight ahead'], other: [] },
  },
  { japanese: { main: ['マッチ'], other: [], kanji: [] }, english: { main: ['matches'], other: [] } },
  { japanese: { main: ['まど'], other: [], kanji: ['窓'] }, english: { main: ['window'], other: [] } },
  { japanese: { main: ['まるい'], other: [], kanji: ['丸い'] }, english: { main: ['round'], other: [] } },
  { japanese: { main: ['まん'], other: [], kanji: ['万'] }, english: { main: ['ten thousand'], other: [] } },
  {
    japanese: { main: ['まんねんひつ'], other: [], kanji: ['万年筆'] },
    english: { main: ['fountain pen'], other: [] },
  },
  { japanese: { main: ['みがく'], other: [], kanji: ['磨く'] }, english: { main: ['to polish'], other: ['to brush'] } },
  { japanese: { main: ['みぎ'], other: [], kanji: ['右'] }, english: { main: ['right'], other: [] } },
  { japanese: { main: ['みじかい'], other: [], kanji: ['短い'] }, english: { main: ['short'], other: [] } },
  { japanese: { main: ['おみず'], other: [], kanji: ['お水'] }, english: { main: ['water'], other: [] } },
  { japanese: { main: ['みせ'], other: [], kanji: ['店'] }, english: { main: ['shop'], other: [] } },
  { japanese: { main: ['みせる'], other: [], kanji: ['見せる'] }, english: { main: ['to look'], other: ['to watch'] } },
  { japanese: { main: ['みち'], other: [], kanji: ['道'] }, english: { main: ['road'], other: [] } },
  {
    japanese: { main: ['みっか'], other: [], kanji: ['三日'] },
    english: { main: ['3rd day of a month'], other: ['3 days'] },
  },
  { japanese: { main: ['みっつ'], other: [], kanji: ['三つ'] }, english: { main: ['three'], other: [] } },
  { japanese: { main: ['みなさん'], other: [], kanji: ['皆さん'] }, english: { main: ['everyone'], other: [] } },
  { japanese: { main: ['みなみ'], other: [], kanji: ['南'] }, english: { main: ['south'], other: [] } },
  { japanese: { main: ['みみ'], other: [], kanji: ['耳'] }, english: { main: ['ear'], other: [] } },
  { japanese: { main: ['みる'], other: [], kanji: ['見る'] }, english: { main: ['to see'], other: ['to watch'] } },
  { japanese: { main: ['みんな'], other: [], kanji: ['皆'] }, english: { main: ['all'], other: ['everyone'] } },
  {
    japanese: { main: ['むいか'], other: [], kanji: ['六日'] },
    english: { main: ['the 6th day of a month'], other: ['6 days'] },
  },
  { japanese: { main: ['むこう'], other: [], kanji: ['向こう'] }, english: { main: ['over there'], other: [] } },
  { japanese: { main: ['むずかしい'], other: [], kanji: ['難しい'] }, english: { main: ['difficult'], other: [] } },
  { japanese: { main: ['むっつ'], other: [], kanji: ['六つ'] }, english: { main: ['six'], other: [] } },
  { japanese: { main: ['め'], other: [], kanji: ['目'] }, english: { main: ['eye'], other: [] } },
  { japanese: { main: ['メートル'], other: [], kanji: [] }, english: { main: ['meter'], other: [] } },
  { japanese: { main: ['めがね'], other: [], kanji: [] }, english: { main: ['a pair of glasses'], other: [] } },
  { japanese: { main: ['もう'], other: [], kanji: [] }, english: { main: ['already'], other: ['yet'] } },
  { japanese: { main: ['もう'], other: [], kanji: [] }, english: { main: ['(one) more'], other: [] } },
  { japanese: { main: ['もくようび'], other: [], kanji: ['木曜日'] }, english: { main: ['Thursday'], other: [] } },
  { japanese: { main: ['もしもし'], other: [], kanji: [] }, english: { main: ['hello on the phone'], other: [] } },
  { japanese: { main: ['もちろん'], other: [], kanji: ['勿論'] }, english: { main: ['of course'], other: [] } },
  { japanese: { main: ['もつ'], other: [], kanji: ['持つ'] }, english: { main: ['to have'], other: ['to own'] } },
  { japanese: { main: ['もっと'], other: [], kanji: [] }, english: { main: ['more'], other: [] } },
  { japanese: { main: ['もの'], other: [], kanji: ['物'] }, english: { main: ['thing'], other: [] } },
  { japanese: { main: ['もん'], other: [], kanji: ['門'] }, english: { main: ['gate'], other: [] } },
  { japanese: { main: ['もんだい'], other: [], kanji: ['問題'] }, english: { main: ['problem'], other: ['question'] } },
  { japanese: { main: ['〜や'], other: [], kanji: ['〜屋'] }, english: { main: ['shop. store'], other: [] } },
  { japanese: { main: ['やおや'], other: [], kanji: ['八百屋'] }, english: { main: ['vegetable shop'], other: [] } },
  { japanese: { main: ['やさい'], other: [], kanji: ['野菜'] }, english: { main: ['vegetable'], other: [] } },
  { japanese: { main: ['やさしい'], other: [], kanji: ['優しい'] }, english: { main: ['gentle'], other: [] } },
  { japanese: { main: ['やすい'], other: [], kanji: ['安い'] }, english: { main: ['cheap'], other: ['inexpensive'] } },
  { japanese: { main: ['やすみ'], other: [], kanji: ['休み'] }, english: { main: ['holiday'], other: ['vacation'] } },
  { japanese: { main: ['やすむ'], other: [], kanji: ['休む'] }, english: { main: ['to rest'], other: [] } },
  { japanese: { main: ['やっつ'], other: [], kanji: ['八つ'] }, english: { main: ['eight'], other: [] } },
  { japanese: { main: ['やま'], other: [], kanji: ['山'] }, english: { main: ['mountain'], other: [] } },
  { japanese: { main: ['やる'], other: [], kanji: [] }, english: { main: ['to do'], other: [] } },
  {
    japanese: { main: ['ようか'], other: [], kanji: ['八日'] },
    english: { main: ['8th day of the month'], other: ['8 days'] },
  },
  {
    japanese: { main: ['ようふく'], other: [], kanji: ['洋服'] },
    english: { main: ['western style clothing'], other: [] },
  },
  { japanese: { main: ['よく'], other: [], kanji: [] }, english: { main: ['often'], other: [] } },
  { japanese: { main: ['よこ'], other: [], kanji: ['横'] }, english: { main: ['horizontal'], other: [] } },
  {
    japanese: { main: ['よっか'], other: [], kanji: ['四日'] },
    english: { main: ['4th day of the month'], other: ['4 days'] },
  },
  { japanese: { main: ['よっつ'], other: [], kanji: ['四つ'] }, english: { main: ['four'], other: [] } },
  { japanese: { main: ['よぶ'], other: [], kanji: ['呼ぶ'] }, english: { main: ['to call'], other: [] } },
  { japanese: { main: ['よむ'], other: [], kanji: ['読む'] }, english: { main: ['to read'], other: [] } },
  { japanese: { main: ['よる'], other: [], kanji: ['夜'] }, english: { main: ['night'], other: [] } },
  { japanese: { main: ['らいげつ'], other: [], kanji: ['来月'] }, english: { main: ['next month'], other: [] } },
  { japanese: { main: ['らいしゅう'], other: [], kanji: ['来週'] }, english: { main: ['next week'], other: [] } },
  { japanese: { main: ['らいねん'], other: [], kanji: ['来年'] }, english: { main: ['next year'], other: [] } },
  { japanese: { main: ['ラジオ'], other: [], kanji: [] }, english: { main: ['radio'], other: [] } },
  { japanese: { main: ['りっぱ'], other: [], kanji: ['立派'] }, english: { main: ['splendid'], other: [] } },
  {
    japanese: { main: ['りゅうがくせい'], other: [], kanji: ['留学生'] },
    english: { main: ['foreign student'], other: [] },
  },
  { japanese: { main: ['りょうしん'], other: [], kanji: ['両親'] }, english: { main: ['parents'], other: [] } },
  { japanese: { main: ['りょうり'], other: [], kanji: ['料理'] }, english: { main: ['cooking'], other: [] } },
  { japanese: { main: ['りょこう'], other: [], kanji: ['旅行'] }, english: { main: ['travel'], other: [] } },
  { japanese: { main: ['れい'], other: [], kanji: [] }, english: { main: ['zero'], other: [] } },
  { japanese: { main: ['れいぞうこ'], other: [], kanji: ['冷蔵庫'] }, english: { main: ['refrigerator'], other: [] } },
  { japanese: { main: ['レコード'], other: [], kanji: [] }, english: { main: ['record'], other: [] } },
  { japanese: { main: ['レストラン'], other: [], kanji: [] }, english: { main: ['restaurant'], other: [] } },
  { japanese: { main: ['れんしゅう'], other: [], kanji: ['練習'] }, english: { main: ['practice'], other: [] } },
  { japanese: { main: ['ろく'], other: [], kanji: ['六'] }, english: { main: ['six'], other: [] } },
  { japanese: { main: ['ワイシャツ'], other: [], kanji: [] }, english: { main: ['white shirt'], other: [] } },
  { japanese: { main: ['わかい'], other: [], kanji: ['若い'] }, english: { main: ['young'], other: [] } },
  {
    japanese: { main: ['わかる'], other: [], kanji: ['分かる'] },
    english: { main: ['to know'], other: ['to understand'] },
  },
  { japanese: { main: ['わすれる'], other: [], kanji: ['忘れる'] }, english: { main: ['to forget'], other: [] } },
  { japanese: { main: ['わたし'], other: [], kanji: ['私'] }, english: { main: ['me'], other: ['I'] } },
  { japanese: { main: ['わたす'], other: [], kanji: ['渡す'] }, english: { main: ['to hand over'], other: [] } },
  { japanese: { main: ['わたる'], other: [], kanji: ['渡る'] }, english: { main: ['to cross'], other: [] } },
  { japanese: { main: ['わるい'], other: [], kanji: ['悪い'] }, english: { main: ['bad'], other: [] } },
]

export default n5Grammar
